parameters:
#    acme_calculator.example.class: Acme\CalculatorModelBundle\Example

services:
  acme.internal.guzzle.provider.cache:
    class: Acme\CalculatorModelBundle\Service\GuzzleClientProvider
    calls:
      - [addCachePlugin, []]